### ISSUE TITLE
Help with plugin

### ISSUE THREAD

**Issue by michaelHeimes** [thednp/contact-form-7-enhancements#1]
Hello. I'm just looking for help with the plugin. I can't find documentation. I activate the plugin and when I click the "quiz" button in Contact Forms 7 an empty box opens.

**Comment by thednp** [comment]
What do you expect it to do? It only does 2 things as stated in the repository description.

Update: @michaelHeimes I confirm there is an issue with editing contact form and the plugin seems to be the reason. I will work a fix for it and will commit asap.

**Comment by thednp** [comment]
Please redownload and test.

**Comment by michaelHeimes** [comment]
@thednp The quiz edit in contact form now works. I still don't know how to add the placeholder within a quiz answer box. I don't know where code such as [watermark "Message"] is supposed to be inserted.

**Comment by thednp** [comment]
Try this shortcode:

```
[quiz random-capital-quiz class:form-control id:Quiz placeholder "The capital of Japan?|Tokyo" "The capital of France?|Paris" "The capital of Madagascar?|Antananarivo"]
```

You only need to mention `placeholder` as a shortcode setting, and the question will be used for your input as placeholder.

**Comment by michaelHeimes** [comment]
Ah! That makes sense. I was thinking that the question would remain outside the answer box. I'll just move the question to a span. Thanks!

**Comment by thednp** [comment]
@michaelHeimes I also updated the [readme](https://github.com/thednp/contact-form-7-enhancements/blob/master/README.md) for a quick guide on how to use it. Make sure to check it, test it and report back.

**Comment by michaelHeimes** [comment]
Yes! That readme would have been a big help for me. Thanks for adding it!

**Comment by thednp** [comment]
Right, now thanks for checking out the plugin.

**Comment by michaelHeimes** [comment]
Thanks for making it!

Like I said, the design I'm coding had the question outside the answer box and a placeholder that was NOT the question. I just made a spn outside of it (for anyone who ends up here with the same problem I had). Works great!
<img width="439" alt="screenshot 2016-06-01 09 33 44" src="https://cloud.githubusercontent.com/assets/13374349/15711475/288b8a26-27dc-11e6-8193-cab0dfb88c71.png">
