### ISSUE TITLE
need update - conflict with cf7 4.6

### ISSUE THREAD

**Issue by mwordpress** [thednp/contact-form-7-enhancements#2]
Does not work with version 4.6

work nice with 4.5.1

thanks for nice plugin

**Comment by thednp** [comment]
Do you have a console error log?

**Comment by mwordpress** [comment]
There is no error in console log

but in debug mode
```
[11-Dec-2016 10:46:27 UTC] PHP Notice:  wpcf7_add_shortcode is <strong>deprecated</strong> since Contact Form 7 version 4.6! Use wpcf7_add_form_tag instead.
```

and i check html with firebug i don't see button tag

sorry formy english ;)

**Comment by thednp** [comment]
OK I got that too, I will check it ASAP.

Thanks for the report.

**Comment by thednp** [comment]
Please download and test latest master.

**Comment by mwordpress** [comment]
Does not work yet 

```markup
<span class="wpcf7-form-control-wrap quiz-841">
  <label><span class="wpcf7-quiz-label">2+7=?</span> <input name="quiz-841" size="40" class="wpcf7-form-control wpcf7-quiz quiz" autocomplete="off" aria-required="true" aria-invalid="false" type="text"></label>
  <input name="_wpcf7_quiz_answer_quiz-841" value="29d2f569ee853761d7c122ebb952e117" type="hidden">
</span>
```

**Comment by mwordpress** [comment]
i think problem from this class "WPCF7_Shortcode" is deprecated

**Comment by thednp** [comment]
It's possible the script also need to get updated, so I will inspect this issue closely and hopefully fix it asap.

I think the CF7 developer changed some class names or something, so I will check it.

**Comment by thednp** [comment]
Issue is now fixed, it's now even less code. We only override the tag handler, so now we can safely close this, please confirm the new version works.

**Warning: the new version is not backward compatible.**

**Comment by Jan120** [comment]
Many thanks for you quick update! I am using a WordPress Multisite (WP 4.7) and the latest Contact Form 7 (4.6). I tried your new version but I got this error while activating your plugin: 

```
Fatal error: Cannot redeclare dnp_add_form_tag_submit() (previously declared in /www/htdocs/w0154758/awila.de/wp-content/plugins/contact-form-7-enhancements-master/submit.php:11) in /www/htdocs/w0154758/awila.de/wp-content/plugins/contact-form-7-enhancements-master/quiz.php on line 12
```

Can you help me with this? Many thanks in advance!

**Comment by thednp** [comment]
I've no exp in multi-site but I will give it a try, you're the one to confirm it will work.

**Comment by thednp** [comment]
OK Please download and try again.

**Comment by Jan120** [comment]
No problem for me now. Works perfectly! Thank you so much for helping out! Your plugin is so useful for me.

**Comment by thednp** [comment]
OK, thanks for reporting, make sure to check close with the project.

**Comment by Jan120** [comment]
Sorry, but I am Newbie here. How do I close with the project?

**Comment by thednp** [comment]
Star it, watch it, and always get news on it here.

**Comment by mwordpress** [comment]
it's working good now 

big thanks and Sorry for the delay

**Comment by mwordpress** [comment]
may be you need to comment this line
`add_action('wp_enqueue_scripts','dnp_enque_cf7e_script');`
no need for script i think

**Comment by thednp** [comment]
@mwordpress that is needed, we override the function for the quiz, please redownload master, and check it. It should work fine now.

**Comment by mwordpress** [comment]
before "cf7e.js" give error 404 in console log and it's ok now
