### ISSUE TITLE
Placeholder is not working.

### ISSUE THREAD

**Issue by ravismakwana** [thednp/contact-form-7-enhancements#4]
I have used this shortcode: 
[quiz math-quiz class:form-control class:outline-none class:shadow-none class:border-0 placeholder "Spamschutz-Frage: 2 + 3 = ?|5"]

I'm not sure why it's not working for me.
![image](https://user-images.githubusercontent.com/37526119/191766641-b32204f6-6bec-40c3-9376-c976d5f6b8ba.png)
As you can see in the screenshot, textare have a placeholder but it is not working with quiz.

Please help.

**Comment by thednp** [comment]
Unfortunately I no longer have time or interest to maintain this snippet.

Have a nice day.
